[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q --tb=short --disable-warnings --maxfail=1 --html=reports/report.html --self-contained-html
markers =
	elements: Add Element test cases
	comments: Comment test cases
	export: Export test cases
	settings: Settings test cases
